# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
