# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-24 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0002_usercompany_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([('company', 'name'), ('name', 'active')]),
        ),
    ]
