# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0005_auto_20161225_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='year_pet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='year_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
