# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0007_auto_20170103_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecompany',
            name='active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='schedulecompanyuser',
            name='active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='weekday',
            name='active',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.IntegerField(default=True),
        ),
    ]
