# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0008_auto_20170112_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True)),
            ],
            options={
                'verbose_name_plural': 'PlanningStatuss',
                'db_table': 'planning_status',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'managed': True, 'verbose_name_plural': 'ProjectsStatuss'},
        ),
        migrations.AddField(
            model_name='petition',
            name='planning_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.PlanningStatus'),
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.PlanningStatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='planning_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.PlanningStatus'),
        ),
    ]
