# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0009_auto_20170115_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='planning_status',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.PlanningStatus'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='planning_status',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.PlanningStatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planning_status',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.PlanningStatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.ProjectStatus'),
        ),
    ]
