# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecompany',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
