# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0002_auto_20160828_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulecompanyuser',
            name='week',
        ),
    ]
