# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0003_remove_schedulecompanyuser_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulecompanyuser',
            old_name='hours',
            new_name='hour',
        ),
    ]
