# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0003_project_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'client'), ('name', 'company')]),
        ),
    ]
