# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0004_auto_20160830_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='planned',
            field=models.BooleanField(default=False),
        ),
    ]
