# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0004_auto_20160824_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedulecompany',
            unique_together=set([('company_week_day', 'company')]),
        ),
    ]
