# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0005_auto_20160824_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='day_week_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='day_week_out',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.Project'),
        ),
        migrations.AlterField(
            model_name='request',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.UserCompany'),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner_app.AuthUser'),
        ),
        migrations.AlterField(
            model_name='request',
            name='week_number',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
